<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
 
class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('products')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
        DB::table('products')->insert([
            ['categories_id' => 7, 'products_name' => 'Chilean Sea Bass Fillet', 'products_description' => 'Premium Chilean sea bass fillets, wild-caught from the cold waters of Chile.', 'products_stock' => 100, 'products_image' => 'sea-bass.jpg', 'hover_image'=>'chilean.jpg', 'unit_price' => 180000, 'orders_price' => 200000, 'rating' => 4.0,'calories' => 200,'protein' => '20g','fat' => '13g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 7, 'products_name' => 'Argentinian Red Shrimp', 'products_description' => 'Large, sweet Argentinian red shrimp, perfect for grilling or sautéing.', 'products_stock' => 100, 'products_image' => 'red-shrimp.jpg', 'hover_image' => 'redargentine.jpeg', 'unit_price' => 200000, 'orders_price' => 220000, 'rating' => 4.5, 'calories' => 180, 'protein' => '23g', 'fat' => '9g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 5, 'products_name' => 'Kanzler Nugget Crispy', 'products_description' => 'Crispy and flavorful chicken nuggets, perfect for quick meals or party snacks.', 'products_stock' => 100, 'products_image' => 'kanzler-nugget.jpg', 'hover_image' => 'kanzlernugget.jpeg', 'unit_price' => 45000, 'orders_price' => 50000, 'rating' => 4.5, 'calories' => 250, 'protein' => '15g', 'fat' => '17g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 1, 'products_name' => 'Ready Meal Fiesta Beef Bulgogi With Rice', 'products_description' => 'Tender beef in a savory bulgogi marinade, perfectly paired with fluffy rice, ideal for a quick and delicious meal.', 'products_stock' => 100, 'products_image' => 'rm-fiesta-bulgogi.jpg', 'hover_image' => 'ricebowl.jpeg', 'unit_price' => 25000, 'orders_price' => 27000, 'rating' => 4.5, 'calories' => 350, 'protein' => '20g', 'fat' => '12g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 7, 'products_name' => 'Gorton\'s Classic Grilled Salmon', 'products_description' => 'Grilled salmon fillets seasoned and ready to enjoy.', 'products_stock' => 100, 'products_image' => 'fish-grilled-salmon.jpg', 'hover_image' => 'salmon.jpeg', 'unit_price' => 50000, 'orders_price' => 56000, 'rating' => 5.0, 'calories' => 210, 'protein' => '22g', 'fat' => '12g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 4, 'products_name' => 'Fiesta Chicken Karaage 500gr', 'products_description' => 'Crispy Japanese-style chicken karaage, made from tender chicken thigh meat. Ready to fry.', 'products_stock' => 100, 'products_image' => 'chicken-fiesta-karage.jpg', 'hover_image' => 'karage.jpeg', 'unit_price' => 46000, 'orders_price' => 48000, 'rating' => 3.5, 'calories' => 290, 'protein' => '18g', 'fat' => '20g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 6, 'products_name' => 'Good Value Mixed Fruit', 'products_description' => 'A convenient mix of frozen strawberries, blueberries, mango, and pineapple. Perfect for smoothies or desserts.', 'products_stock' => 100, 'products_image' => 'gv-mixed-fruit.jpg', 'hover_image' => 'fruitsalad.jpeg', 'unit_price' => 30000, 'orders_price' => 32000, 'rating' => 5.0, 'calories' => 160, 'protein' => '1g', 'fat' => '0g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 2, 'products_name' => 'Golden Farm Mixed Vegetable', 'products_description' => 'A healthy blend of frozen carrots, corn, green beans, and peas. Great for stir-fries or soups.', 'products_stock' => 100, 'products_image' => 'gf-mixedvegetables.jpg', 'hover_image' => 'mixedvege.jpeg', 'unit_price' => 23000, 'orders_price' => 25000, 'rating' => 4.0, 'calories' => 90, 'protein' => '3g', 'fat' => '0.5g','created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 3, 'products_name' => 'Fiesta Siomay', 'products_description' => 'Delicious and ready-to-steam chicken siomay, perfect for snacks or side dishes.', 'products_stock' => 100, 'products_image' => 'fiesta-siomay.jpeg', 'hover_image' => 'fiestasomay.jpeg', 'unit_price' => 32000, 'orders_price' => 34000, 'rating' => 4.0, 'calories' => 190, 'protein' => '8g', 'fat' => '9g',  'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 4, 'products_name' => 'Frozen Beef Meatball', 'products_description' => 'Savory beef meatballs, ready to cook.', 'products_stock' => 80, 'products_image' => 'beef-meatball.jpg', 'hover_image' => 'beef-meatball-hover.jpg', 'unit_price' => 38000, 'orders_price' => 40000, 'rating' => 4.3, 'calories' => 270, 'protein' => '18g', 'fat' => '15g',  'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 5, 'products_name' => 'Chicken Nugget Original', 'products_description' => 'Classic chicken nuggets, crispy outside and juicy inside.', 'products_stock' => 100, 'products_image' => 'nugget-original.jpg', 'hover_image' => 'nugget-original-hover.jpg', 'unit_price' => 42000, 'orders_price' => 45000, 'rating' => 4.5, 'calories' => 260, 'protein' => '14g', 'fat' => '17g',  'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 1, 'products_name' => 'Korean BBQ Chicken Bowl', 'products_description' => 'Ready meal with grilled chicken, rice, and Korean-style BBQ sauce.', 'products_stock' => 70, 'products_image' => 'korean-bowl.jpg', 'hover_image' => 'korean-bowl-hover.jpg', 'unit_price' => 28000, 'orders_price' => 30000, 'rating' => 4.6, 'calories' => 400, 'protein' => '24g', 'fat' => '14g',  'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 8, 'products_name' => 'Matcha Lava Cake', 'products_description' => 'Rich matcha dessert with melting center.', 'products_stock' => 60, 'products_image' => 'matcha-lava.jpg', 'hover_image' => 'matcha-lava-hover.jpg', 'unit_price' => 24000, 'orders_price' => 26000, 'rating' => 4.7, 'calories' => 330, 'protein' => '6g', 'fat' => '20g',  'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 4, 'products_name' => 'Sliced Beef Striploin', 'products_description' => 'Premium striploin slices, perfect for grilling.', 'products_stock' => 50, 'products_image' => 'beef-striploin.jpg', 'hover_image' => 'striploin-hover.jpg', 'unit_price' => 95000, 'orders_price' => 100000, 'rating' => 4.9, 'calories' => 350, 'protein' => '25g', 'fat' => '22g',  'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 6, 'products_name' => 'Tropical Smoothie Mix', 'products_description' => 'Frozen blend of mango, pineapple, and banana.', 'products_stock' => 120, 'products_image' => 'smoothie-mix.jpg', 'hover_image' => 'smoothie-hover.jpg', 'unit_price' => 28000, 'orders_price' => 30000, 'rating' => 4.4, 'calories' => 150, 'protein' => '2g', 'fat' => '1g',  'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 3, 'products_name' => 'Shrimp Siomay', 'products_description' => 'Juicy shrimp siomay with dipping sauce included.', 'products_stock' => 90, 'products_image' => 'shrimp-siomay.jpg', 'hover_image' => 'shrimp-siomay-hover.jpg', 'unit_price' => 32000, 'orders_price' => 35000, 'rating' => 4.2, 'calories' => 200, 'protein' => '10g', 'fat' => '8g',  'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 5, 'products_name' => 'Spicy Chicken Nugget', 'products_description' => 'Spicy and crispy chicken nuggets for spicy food lovers.', 'products_stock' => 100, 'products_image' => 'spicy-nugget.jpg', 'hover_image' => 'spicy-nugget-hover.jpg', 'unit_price' => 46000, 'orders_price' => 48000, 'rating' => 4.6, 'calories' => 270, 'protein' => '16g', 'fat' => '18g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
            ['categories_id' => 4, 'products_name' => 'Mini Chicken Karaage', 'products_description' => 'Bite-size Japanese karaage, easy to fry.', 'products_stock' => 90, 'products_image' => 'mini-karaage.jpg', 'hover_image' => 'mini-karaage-hover.jpg', 'unit_price' => 38000, 'orders_price' => 40000, 'rating' => 4.3, 'calories' => 280, 'protein' => '17g', 'fat' => '19g', 'created_at' => now(), 'updated_at' => now(), 'status_del' => false],
        ]);  
    }
}
